### ISSUE TITLE
Weird Crash thing.

### ISSUE THREAD

**Issue by HockeyD8** [matkoniecz/AIAI#59]
This was probably caused by me switching to AIAI's company and then blowing up its road+station, but it crashed. here is report.
![aiai crash 1](https://user-images.githubusercontent.com/34627054/36074031-0c2d50b6-0f08-11e8-957a-929013590d0b.PNG)

**Comment by matkoniecz** [comment]
> switching to AIAI's company and then blowing up its road+station

Unfortunately this is not supported, this AI remembers locations of its stations/depots and is unable to handle situation where human changes it.

Generally, human switching to AI company may do such weird things that it is not viable to support it.

**Comment by HockeyD8** [comment]
Ok, Thanks For the Info!

**Comment by matkoniecz** [comment]
Also, by reminding me that somebody is still using it you increased chance that I will look at my oldest real programming project :)

**Comment by HockeyD8** [comment]
👍
